// lib/checks/patterns.ts

export const PATTERNS = {
  // Broken href patterns
  BROKEN_HREFS: [
    '',
    '#',
    'javascript:void(0)',
    'javascript:void(0);',
    'javascript:;',
    'javascript:',
    '#!',
    '#/',
  ],

  // Generic anchor texts (English + Georgian)
  GENERIC_ANCHORS: [
    'click here',
    'read more',
    'here',
    'learn more',
    'more',
    'link',
    'this',
    'click',
    'go',
    'see more',
    'view more',
    'continue',
    'details',
    // Georgian
    'წაიკითხეთ მეტი',
    'მეტი',
    'აქ',
    'ვრცლად',
    'დეტალები',
    'გაგრძელება',
    'იხილეთ',
    'ნახეთ',
    'გადასვლა',
  ],

  // AI content detection phrases
  AI_PHRASES: [
    'delve into',
    'delve deeper',
    'dive into',
    'dive deeper',
    'it is important to note',
    'it is worth noting',
    'it is crucial to',
    'in conclusion',
    'to summarize',
    'in summary',
    'moreover',
    'furthermore',
    'additionally',
    'consequently',
    'leverage',
    'utilize',
    'facilitate',
    'implement',
    "in today's digital landscape",
    "in today's world",
    'in this day and age',
    'game-changer',
    'game changer',
    'cutting-edge',
    'cutting edge',
    'unlock the potential',
    'unlock your potential',
    'unleash',
    'seamlessly',
    'effortlessly',
    'streamline',
    'comprehensive guide',
    'ultimate guide',
    'complete guide',
    'crucial aspect',
    'key aspect',
    'important aspect',
    'plays a vital role',
    'plays a crucial role',
    'plays an important role',
    'embark on',
    'embark upon',
    'navigate the complexities',
    'navigate through',
    'holistic approach',
    'robust',
    'scalable',
    'empower',
    'synergy',
    'paradigm',
    'ecosystem',
    'landscape',
  ],

  // CMS detection patterns
  CMS: [
    { name: 'WordPress', patterns: ['wp-content', 'wp-includes', 'wp-json', '/wp-admin'] },
    { name: 'Shopify', patterns: ['shopify', 'cdn.shopify', 'myshopify.com'] },
    { name: 'Wix', patterns: ['wix.com', 'wixstatic', 'parastorage.com'] },
    { name: 'Squarespace', patterns: ['squarespace', 'sqsp.net', 'static1.squarespace'] },
    { name: 'Webflow', patterns: ['webflow', 'assets.website-files.com'] },
    { name: 'Drupal', patterns: ['drupal', '/sites/default/files', 'drupal.settings'] },
    { name: 'Joomla', patterns: ['joomla', '/media/system/js', 'com_content'] },
    { name: 'Magento', patterns: ['magento', 'mage/', 'requirejs/require'] },
    { name: 'PrestaShop', patterns: ['prestashop', '/modules/ps_'] },
    { name: 'BigCommerce', patterns: ['bigcommerce', 'cdn11.bigcommerce'] },
    { name: 'Ghost', patterns: ['ghost', 'ghost-url', 'ghost/api'] },
    { name: 'HubSpot', patterns: ['hubspot', 'hs-scripts.com', 'hubspotusercontent'] },
    { name: 'Contentful', patterns: ['contentful', 'ctfassets.net'] },
    { name: 'Sanity', patterns: ['sanity.io', 'cdn.sanity.io'] },
    { name: 'Tilda', patterns: ['tilda', 'tildacdn.com'] },
    { name: 'Blogger', patterns: ['blogger.com', 'blogspot.com'] },
    { name: 'Medium', patterns: ['medium.com', 'cdn-images-1.medium.com'] },
  ],

  // Framework detection patterns
  FRAMEWORKS: [
    { name: 'Next.js', patterns: ['__next', '_next/static', '__next_data__', 'next/dist'] },
    { name: 'Nuxt.js', patterns: ['__nuxt', '_nuxt/', 'nuxt', 'nuxtjs'] },
    { name: 'Gatsby', patterns: ['gatsby', '___gatsby', 'gatsby-image'] },
    { name: 'React', patterns: ['react-root', '_reactroot', 'data-reactid', 'data-reactroot'] },
    { name: 'Vue.js', patterns: ['data-v-', '__vue__', 'vue-router', 'vuex'] },
    { name: 'Angular', patterns: ['ng-version', 'ng-app', '_ngcontent', 'angular'] },
    { name: 'Svelte', patterns: ['svelte', '__svelte'] },
    { name: 'Astro', patterns: ['astro', 'astro-island'] },
    { name: 'Remix', patterns: ['remix', '__remix'] },
    { name: 'Ember', patterns: ['ember', 'data-ember'] },
    { name: 'Laravel', patterns: ['laravel', 'laravel_session'] },
    { name: 'Ruby on Rails', patterns: ['data-turbolinks', 'csrf-token'] },
    { name: 'Django', patterns: ['csrfmiddlewaretoken', 'django'] },
    { name: 'Bootstrap', patterns: ['bootstrap', 'cdn.jsdelivr.net/npm/bootstrap'] },
    { name: 'Tailwind CSS', patterns: ['tailwindcss', 'tailwind'] },
  ],

  // Social platform detection
  SOCIAL_PLATFORMS: [
    { name: 'Facebook', pattern: 'facebook.com' },
    { name: 'Twitter/X', pattern: 'twitter.com' },
    { name: 'X', pattern: 'x.com' },
    { name: 'LinkedIn', pattern: 'linkedin.com' },
    { name: 'Instagram', pattern: 'instagram.com' },
    { name: 'YouTube', pattern: 'youtube.com' },
    { name: 'TikTok', pattern: 'tiktok.com' },
    { name: 'Pinterest', pattern: 'pinterest.com' },
    { name: 'Telegram', pattern: 't.me' },
    { name: 'WhatsApp', pattern: 'wa.me' },
    { name: 'Discord', pattern: 'discord.gg' },
    { name: 'Reddit', pattern: 'reddit.com' },
    { name: 'GitHub', pattern: 'github.com' },
    { name: 'Dribbble', pattern: 'dribbble.com' },
    { name: 'Behance', pattern: 'behance.net' },
  ],

  // Schema.org required fields by type
  SCHEMA_REQUIREMENTS: {
    Product: {
      required: ['name', 'image'],
      recommended: ['description', 'offers', 'review', 'aggregateRating', 'brand', 'sku'],
      needsOneOf: ['offers', 'review', 'aggregateRating'],
    },
    Article: {
      required: ['headline', 'datePublished', 'author'],
      recommended: ['image', 'dateModified', 'publisher'],
    },
    BlogPosting: {
      required: ['headline', 'datePublished', 'author'],
      recommended: ['image', 'dateModified', 'publisher'],
    },
    NewsArticle: {
      required: ['headline', 'datePublished', 'author', 'dateModified'],
      recommended: ['image', 'publisher'],
    },
    Organization: {
      required: ['name'],
      recommended: ['url', 'logo', 'contactPoint', 'sameAs'],
    },
    LocalBusiness: {
      required: ['name', 'address'],
      recommended: ['telephone', 'url', 'openingHours', 'image', 'priceRange'],
    },
    FAQPage: {
      required: ['mainEntity'],
    },
    BreadcrumbList: {
      required: ['itemListElement'],
    },
    WebSite: {
      recommended: ['name', 'url', 'potentialAction'],
    },
    Person: {
      required: ['name'],
      recommended: ['url', 'image', 'jobTitle'],
    },
    Event: {
      required: ['name', 'startDate', 'location'],
      recommended: ['endDate', 'description', 'image', 'offers'],
    },
    Recipe: {
      required: ['name', 'image'],
      recommended: ['author', 'datePublished', 'description', 'recipeIngredient', 'recipeInstructions'],
    },
    Review: {
      required: ['itemReviewed', 'author'],
      recommended: ['reviewRating', 'datePublished'],
    },
    VideoObject: {
      required: ['name', 'description', 'thumbnailUrl', 'uploadDate'],
      recommended: ['duration', 'contentUrl', 'embedUrl'],
    },
    HowTo: {
      required: ['name', 'step'],
      recommended: ['description', 'image', 'totalTime'],
    },
  } as Record<string, { required?: string[]; recommended?: string[]; needsOneOf?: string[] }>,

  // Valid ISO 639-1 language codes
  VALID_LANG_CODES: [
    'aa', 'ab', 'ae', 'af', 'ak', 'am', 'an', 'ar', 'as', 'av', 'ay', 'az',
    'ba', 'be', 'bg', 'bh', 'bi', 'bm', 'bn', 'bo', 'br', 'bs',
    'ca', 'ce', 'ch', 'co', 'cr', 'cs', 'cu', 'cv', 'cy',
    'da', 'de', 'dv', 'dz',
    'ee', 'el', 'en', 'eo', 'es', 'et', 'eu',
    'fa', 'ff', 'fi', 'fj', 'fo', 'fr', 'fy',
    'ga', 'gd', 'gl', 'gn', 'gu', 'gv',
    'ha', 'he', 'hi', 'ho', 'hr', 'ht', 'hu', 'hy', 'hz',
    'ia', 'id', 'ie', 'ig', 'ii', 'ik', 'io', 'is', 'it', 'iu',
    'ja', 'jv',
    'ka', 'kg', 'ki', 'kj', 'kk', 'kl', 'km', 'kn', 'ko', 'kr', 'ks', 'ku', 'kv', 'kw', 'ky',
    'la', 'lb', 'lg', 'li', 'ln', 'lo', 'lt', 'lu', 'lv',
    'mg', 'mh', 'mi', 'mk', 'ml', 'mn', 'mr', 'ms', 'mt', 'my',
    'na', 'nb', 'nd', 'ne', 'ng', 'nl', 'nn', 'no', 'nr', 'nv', 'ny',
    'oc', 'oj', 'om', 'or', 'os',
    'pa', 'pi', 'pl', 'ps', 'pt',
    'qu',
    'rm', 'rn', 'ro', 'ru', 'rw',
    'sa', 'sc', 'sd', 'se', 'sg', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'ss', 'st', 'su', 'sv', 'sw',
    'ta', 'te', 'tg', 'th', 'ti', 'tk', 'tl', 'tn', 'to', 'tr', 'ts', 'tt', 'tw', 'ty',
    'ug', 'uk', 'ur', 'uz',
    've', 'vi', 'vo',
    'wa', 'wo',
    'xh',
    'yi', 'yo',
    'za', 'zh', 'zu',
  ],
};
